-- Auto-generated by Matugen
require("mini.base16").setup({
	palette = {
		--  Default Background
		base00 = "{{ colors.surface_container_low.default.hex }}",
		--  Lighter Background (Used for status bars, line number and folding marks)
		base01 = "{{ colors.surface_container_high.default.hex }}",
		--  Selection Background
		base02 = "{{ colors.outline_variant.default.hex }}",
		--  Comments, Invisibles, Line Highlighting
		-- Actually numbers on left bar
		base03 = "{{ colors.on_surface_variant.default.hex }}",
		--  Dark Foreground (Used for status bars)
		-- Actually main number on left bar
		base04 = "{{ colors.on_surface.default.hex }}",
		--  Default Foreground, Caret, Delimiters, Operators
		--  Actually Variables
		base05 = "{{ colors.turquoise.default.hex | auto_lightness: 20.0 }}",
		--  Light Foreground (Not often used)
		base06 = "#00ff00",
		--  Light Background (Not often used)
		base07 = "#0000ff",

		--  Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
		--  Actually Identifiers
		base08 = "{{ colors.orange.default.hex | auto_lightness: -10.0 }}",
		--  Integers, Boolean, Constants, XML Attributes, Markup Link Url
		base09 = "{{ colors.purple.default.hex | auto_lightness: 20.0 }}",
		--  Classes, Markup Bold, Search Text Background
		base0A = "{{ colors.blue.default.hex | auto_lightness: 20.0 }}",
		--  Strings, Inherited Class, Markup Code, Diff Inserted
		base0B = "{{ colors.on_khaki_container.default.hex | auto_lightness: 10.0 }}",
		--  Support, Regular Expressions, Escape Characters, Markup Quotes
		base0C = "{{ colors.blueviolet.default.hex | auto_lightness: 10.0 }}",
		--  Functions, Methods, Attribute IDs, Headings
		base0D = "{{ colors.springgreen.default.hex | auto_lightness: 20.0 }}",
		--  Keywords, Storage, Selector, Markup Italic, Diff Changed
		base0E = "{{ colors.red.default.hex | auto_lightness: 25.0 }}",
		--  Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
		base0F = "{{ colors.brown_container.default.hex | auto_lightness: 20.0 }}",
	},
	use_cterm = true,
	transparent = true,
	plugins = {
		default = true,
		-- default = false,
		-- ["nvim-mini/mini.nvim"] = true,
	},
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

set_hl_mutliple({ "TSComment", "Comment" }, {
	bg = "{{ colors.red_container.default.hex | auto_lightness: -25.0 }}",
	fg = "{{ colors.red_source.default.hex | auto_lightness: -10.0 }}",
})

set_hl_mutliple({
	"NormalFloat",
	"Normal",
	"NonText",
	"BufferInactive",
	"NormalNC",
	-- "Comment",
	-- "Constant",
	-- "Special",
	-- "Identifier",
	-- "Statement",
	-- "PreProc",
	-- "Type",
	-- "Underlined",
	-- "Todo",
	-- "String",
	-- "Function",
	-- "Conditional",
	-- "Repeat",
	-- "Operator",
	-- "Structure",
	-- "LineNr",
	-- "SignColumn",
	"CursorLine",
	-- "CursorLineNr",
	-- "StatusLine",
	-- "StatusLineNC",
	-- "EndOfBuffer",
	"NeoTreeNormal",
	"NeoTreeNormalNC",
}, {
	bg = "NONE",
})

local function link_hl_mutliple(links)
	for k, v in pairs(links) do
		vim.api.nvim_set_hl(0, k, { link = v })
	end
end

link_hl_mutliple({
	-- ["@lsp"] = "@type",
	["@lsp.type.class"] = "@type",
	["@lsp.type.event"] = "@type",
	["@lsp.type.function"] = "@function",
	["@lsp.type.interface"] = "@type",
	["@lsp.type.macro"] = "@constant.macro",
	-- ["@lsp.type.macro"] = "@constant",
	["@lsp.type.method"] = "@function.method",
	-- ["@lsp.type.method"] = "@function",
	["@lsp.type.modifier"] = "@type.qualifier",
	-- ["@lsp.type.modifier"] = "@type",
	["@lsp.type.regexp"] = "@string.regexp",
	["@lsp.type.struct"] = "@type",
	["@lsp.type.type"] = "@type",
	["@lsp.type.typeParameter"] = "@type.definition",
	-- ["@lsp.type.typeParameter"] = "@type",
	["@lsp.type.variable"] = "@variable",
	["@lsp.type.member"] = "Identifier",
	["@lsp.mod.deprecated"] = "DiagnosticDeprecated",
})

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "{{ colors.primary_container.default.hex }}",
	fg = "{{ colors.background.default.hex }}",
})

-- set_hl_mutliple({ "TSMethod", "Method" }, {
-- 	fg = "{{ colors.tertiary.default.hex }}",
-- })
--
-- set_hl_mutliple({ "TSFunction", "Function" }, {
-- 	fg = "{{ colors.secondary.default.hex }}",
-- })
--
-- vim.api.nvim_set_hl(0, "Keyword", {
--   -- fg = "{{ colors.inverse_primary.default.hex }}",
--   fg = "{{ colors.primary.default.hex }}",
-- })
--

vim.api.nvim_set_hl(0, "MsgArea", {
	bg = "{{ colors.inverse_on_surface.default.hex }}",
	fg = "{{ colors.primary.default.hex }}",
})

vim.api.nvim_set_hl(0, "DiffText", { bg = "NONE" })
vim.api.nvim_set_hl(0, "DiffAdd", { bg = "{{ colors.lime_container.default.hex }}" })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = "{{ colors.red_container.default.hex }}" })
vim.api.nvim_set_hl(0, "DiffChange", { bg = "{{ colors.orange_container.default.hex | auto_lightness: -5.0 }}" })

vim.api.nvim_set_hl(0, "DiffviewDiffAddAsDelete", {
	bg = "{{ colors.red_source.default.hex | auto_lightness: 25.0 }}",
	fg = "{{ colors.red_source.default.hex | auto_lightness: 40.0 }}",
})
vim.api.nvim_set_hl(0, "DiffviewDiffAdd", {
	bg = "{{ colors.lime_container.default.hex | auto_lightness: 10.0 }}",
	fg = "{{ colors.on_lime_container.default.hex | auto_lightness: -10.0 }}",
})

-- Be sure to add this hook on the Diffview setup:
-- require('diffview').setup {
--   hooks = {
--     -- Taken from this example: https://github.com/sindrets/diffview.nvim/pull/258#issuecomment-1408689220
--     diff_buf_win_enter = function(bufnr, winid, ctx)
--       if ctx.layout_name:match '^diff2' then
--         if ctx.symbol == 'a' then
--           vim.opt_local.winhl = table.concat({
--             'DiffText:DiffviewDiffAddAsDelete',
--             'DiffChange:DiffviewLineChangeDiffDelete',
--           }, ',')
--         elseif ctx.symbol == 'b' then
--           vim.opt_local.winhl = table.concat({
--             'DiffText:DiffviewDiffAdd',
--             'DiffChange:DiffviewLineChangeDiffAdd',
--           }, ',')
--         end
--       end
--     end,
--   },
-- }

vim.api.nvim_set_hl(0, "DiffviewLineChangeDiffDelete", {
	bg = "{{ colors.red_container.default.hex | auto_lightness: -10.0 }}",
})
vim.api.nvim_set_hl(0, "DiffviewLineChangeDiffAdd", {
	bg = "{{ colors.lime_container.default.hex | auto_lightness: -07.0 }}",
})
