-- -- ============================================================
-- -- Converted from hyprland.conf (hyprlang) to hyprland.lua
-- -- (Hyprland's Lua config format, introduced in 0.55)
-- --
-- -- Assumption: the original file referenced $mainMod, which is
-- -- almost always defined as SUPER. Change this if yours differs.
-- -- ============================================================
--
-- local mainMod = "SUPER"
--
-- -- Small helper so key combos read like the old "$mainMod SHIFT, key" style
-- local function combo(...)
--   return table.concat({ ... }, " + ")
-- end
--
-- -- ======= Window Actions =======
--
-- -- Move window with mainMod + LMB and dragging
-- hl.bind(combo(mainMod, "mouse:272"), hl.dsp.window.drag(),
--   { drag = true, desc = "Move the window towards a direction" })
--
-- -- Move window / focus / workspace towards a direction
-- -- (arrow keys + vim-style HJKL aliases, just like the original)
-- local directions = {
--   { dir = "left",  keys = { "left",  "H" } },
--   { dir = "right", keys = { "right", "L" } },
--   { dir = "up",    keys = { "up",    "K" } },
--   { dir = "down",  keys = { "down",  "J" } },
-- }
--
-- for _, d in ipairs(directions) do
--   for _, key in ipairs(d.keys) do
--     -- Move active window in a direction
--     hl.bind(combo(mainMod, "SHIFT", key), hl.dsp.window.move({ direction = d.dir }),
--       { desc = "Move active window " .. d.dir .. "wards" })
--
--     -- moveoutofgroup + movewindoworgroup combined
--     -- (original bound both dispatchers to the same key)
--     hl.bind(combo(mainMod, "ALT", key), function()
--       hl.dispatch(hl.dsp.window.move({ out_of_group = d.dir }))
--       hl.dispatch(hl.dsp.window.move({ direction = d.dir, group_aware = true }))
--     end, { desc = "Move active window to the " .. d.dir })
--
--     -- Move active workspace to the monitor in that direction
--     hl.bind(combo(mainMod, "CTRL", key), hl.dsp.workspace.move({ monitor = d.dir:sub(1, 1) }),
--       { desc = "Move active workspace to monitor " .. d.dir .. "wards" })
--
--     -- Move keyboard focus in a direction
--     hl.bind(combo(mainMod, key), hl.dsp.focus({ direction = d.dir }),
--       { desc = "Move focus " .. d.dir .. "wards" })
--   end
-- end
--
-- hl.bind(combo(mainMod, "SHIFT", "slash"), hl.dsp.window.center(),
--   { desc = "Center active window downwards" })
--
-- hl.bind(combo(mainMod, "CTRL", "Tab"), hl.dsp.focus({ monitor = "+" }),
--   { desc = "Move focus to next monitor" })
-- hl.bind(combo(mainMod, "ALT", "Tab"), hl.dsp.focus({ monitor = "+" }),
--   { desc = "Move focus to next monitor" })
--
-- hl.bind(combo(mainMod, "minus"), hl.dsp.exec_cmd("hyprctl dispatch hyprwinwrap_interactivity"),
--   { desc = "Toggle hyprwinwrap interactivity" })
--
-- -- ## Resizing windows ##
--
-- -- Activate keyboard window resize mode (left commented out, as in the original)
-- -- hl.bind(combo(mainMod, "R"), hl.dsp.submap("resize"), { desc = "Activates window resizing mode" })
--
-- local resizeSteps = {
--   { keys = { "right", "l" }, x = 30,  y = 0 },
--   { keys = { "left",  "h" }, x = -30, y = 0 },
--   { keys = { "up",    "k" }, x = 0,   y = -30 },
--   { keys = { "down",  "j" }, x = 0,   y = 30 },
-- }
--
-- hl.define_submap("resize", function()
--   for _, step in ipairs(resizeSteps) do
--     for _, key in ipairs(step.keys) do
--       hl.bind(key, hl.dsp.window.resize({ x = step.x, y = step.y }), { repeating = true })
--     end
--   end
--   -- Ends window resizing mode
--   hl.bind("escape", hl.dsp.submap("reset"))
-- end)
--
-- -- Quick resize window with keyboard
-- -- (mainMod added since CTRL+SHIFT is used for word selection in text editors)
-- for _, step in ipairs(resizeSteps) do
--   for _, key in ipairs(step.keys) do
--     hl.bind(combo(mainMod, "CTRL", "SHIFT", key), hl.dsp.window.resize({ x = step.x, y = step.y }),
--       { repeating = true })
--   end
-- end
--
-- -- Resize / move window with mainMod + LMB/RMB and dragging
-- hl.bind(combo(mainMod, "mouse:273"), hl.dsp.window.resize(),
--   { drag = true, desc = "Resize the window towards a direction" })
-- hl.bind(combo(mainMod, "mouse:272"), hl.dsp.window.drag(),
--   { drag = true, desc = "Drag window" })
-- -- ## Resizing Windows End ##
--
-- -- Move active window to a workspace with mainMod + CTRL + [0-9]
-- for i = 1, 10 do
--   local key = (i == 10) and "0" or tostring(i)
--   local ws  = tostring(i == 10 and 10 or i)
--   hl.bind(combo(mainMod, "CTRL", key), hl.dsp.window.move({ workspace = ws }),
--     { desc = "Move window and switch to workspace " .. ws })
-- end
-- hl.bind(combo(mainMod, "CTRL", "M"), hl.dsp.window.move({ workspace = "special:音楽" }),
--   { desc = "Move window and switch to music workspace" })
-- hl.bind(combo(mainMod, "CTRL", "left"), hl.dsp.window.move({ workspace = "-1" }),
--   { desc = "Move window and switch to the next workspace" })
-- hl.bind(combo(mainMod, "CTRL", "right"), hl.dsp.window.move({ workspace = "+1" }),
--   { desc = "Move window and switch to the previous workspace" })
--
-- -- Same as above, but doesn't switch to the workspace
-- for i = 1, 10 do
--   local key = (i == 10) and "0" or tostring(i)
--   local ws  = tostring(i == 10 and 10 or i)
--   hl.bind(combo(mainMod, "SHIFT", key), hl.dsp.window.move({ workspace = ws, follow = false }),
--     { desc = "Move window silently to workspace " .. ws })
-- end
-- hl.bind(combo(mainMod, "SHIFT", "M"), hl.dsp.window.move({ workspace = "special:音楽", follow = false }),
--   { desc = "Move window silently to music workspace" })
-- hl.bind(combo(mainMod, "SHIFT", "left"), hl.dsp.window.move({ workspace = "-1", follow = false }),
--   { desc = "Move window silently to the next workspace" })
-- hl.bind(combo(mainMod, "SHIFT", "right"), hl.dsp.window.move({ workspace = "+1", follow = false }),
--   { desc = "Move window silently to the previous workspace" })
-- -- Window actions End #
--
-- -- ======= Workspace Actions =======
--
-- -- Switch workspaces with mainMod + [0-9]
-- for i = 1, 10 do
--   local key = (i == 10) and "0" or tostring(i)
--   local ws  = tostring(i == 10 and 10 or i)
--   hl.bind(combo(mainMod, key), hl.dsp.focus({ workspace = ws }),
--     { desc = "Switch to workspace " .. ws })
--
--   -- Move active workspace to the current monitor and switch to it
--   hl.bind(combo(mainMod, "ALT", key), function()
--     hl.dispatch(hl.dsp.workspace.move({ workspace = ws, monitor = "current" }))
--     hl.dispatch(hl.dsp.focus({ workspace = ws }))
--   end, { desc = "Move workspace " .. ws .. " to current monitor and switch to it" })
-- end
--
-- -- Scroll through existing workspaces with mainMod + scroll
-- hl.bind(combo(mainMod, "mouse_down"), hl.dsp.focus({ workspace = "e+1" }),
--   { desc = "Scroll through workspaces incrementally" })
-- hl.bind(combo(mainMod, "mouse_up"), hl.dsp.focus({ workspace = "e-1" }),
--   { desc = "Scroll through workspaces decrementally" })
-- hl.bind(combo(mainMod, "slash"), hl.dsp.focus({ workspace = "previous" }),
--   { desc = "Switch to the previous workspace" })
--
-- -- Special workspaces (scratchpads)
-- hl.bind(combo(mainMod, "CTRL", "equal"), hl.dsp.window.move({ workspace = "special:特別" }),
--   { desc = "Move active window to Special workspace" })
-- hl.bind(combo(mainMod, "SHIFT", "equal"), hl.dsp.window.move({ workspace = "special:特別", follow = false }),
--   { desc = "Move active window silently to Special workspace" })
-- hl.bind(combo(mainMod, "equal"), hl.dsp.workspace.toggle_special("特別"),
--   { desc = "Toggles the Special workspace" })
-- hl.bind(combo(mainMod, "M"), hl.dsp.workspace.toggle_special("音楽"),
--   { desc = "Toggles the Music workspace" })
-- hl.bind(combo(mainMod, "F1"), hl.dsp.workspace.toggle_special("scratchpad"),
--   { desc = "Call special workspace scratchpad" })
-- hl.bind(combo(mainMod, "ALT", "SHIFT", "F1"), hl.dsp.window.move({ workspace = "special:scratchpad", follow = false }),
--   { desc = "Move active window to special workspace scratchpad" })
--
-- -- ======= Others =======
-- hl.bind(combo(mainMod, "SHIFT", "P"), hl.dsp.exec_cmd("hyprpicker -a"),
--   { desc = "Open color picker" })
--
-- -- ======= Additional Settings =======
-- -- https://wiki.hypr.land/Configuring/Basics/Binds/
-- hl.config({
--   binds = {
--     hide_special_on_workspace_change = true,
--     workspace_back_and_forth = false,
--     allow_workspace_cycles = true,
--     workspace_center_on = true,
--     focus_preferred_method = 1,
--     movefocus_cycles_fullscreen = true,
--     window_direction_monitor_fallback = true,
--     disable_keybind_grabbing = true,
--     allow_pin_fullscreen = true,
--     drag_threshold = 1,
--   },
-- })
--
-- -- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- -- ┃                    Gestures                                 ┃
-- -- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
--
-- -- 4-finger horizontal swipe to switch workspaces
-- hl.gesture({ fingers = 4, direction = "horizontal", action = "workspace" })
--
-- -- 3-finger swipe down toggles fullscreen
-- hl.gesture({ fingers = 3, direction = "down", action = "float" })
--
-- -- 3-finger swipe up toggles float/tile
-- hl.gesture({ fingers = 3, direction = "up", action = "fullscreen" })
--
-- -- 3-finger swipe left closes active window
-- -- hl.gesture({ fingers = 3, direction = "left", action = "close" })
--
-- -- 2-finger pinch (with mainMod held) to resize
-- -- Note: the Lua gesture API's `direction` enum doesn't list "pinch" explicitly;
-- -- this is the closest equivalent (mods-gated resize gesture) and is worth
-- -- testing against `gesture = 2, pinch, mod:$mainMod, resize` behavior.
-- hl.gesture({ fingers = 2, direction = "any", mods = mainMod, action = "resize" })
